name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.x'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} ${{ matrix.dependencies }}'
        runs-on: ubuntu-22.04

        strategy:
            fail-fast: false

            matrix:
                include:
                    - php-version: '7.4'
                      dependencies: 'lowest'
                    - php-version: '7.4'
                    - php-version: '8.0'
                    - php-version: '8.1'
                    - php-version: '8.2'
                    - php-version: '8.3'

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Cache Jackrabbit
              id: cache-jackrabbit
              uses: actions/cache@v3
              with:
                path: bin/jackrabbit-standalone-*
                key: jackrabbit

            # default java installation not able to run newer versions of jackrabbit
            - name: Install and configure Java
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: '8'

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: Get source version of phpcr-utils
              run: |
                  rm -rf vendor/phpcr/phpcr-utils
                  composer update phpcr/phpcr-utils --prefer-source

            - name: Start jackrabbit
              run: bin/jackrabbit.sh

            - name: Execute test cases
              run: vendor/bin/phpunit

            - name: Print Jackrabbit logs on error
              if: ${{ failure() }}
              run: cat bin/jackrabbit/log/*
